### ISSUE TITLE
Warning on count() method - php7.2+ at OpenMage LTS 19.4.15

### ISSUE THREAD

**Issue by xavitriu** [OpenMage/magento-lts#1811]
In our slightly modified version of magento lts, we are getting a not countable warning in line 57 on file htdocs/app/code/core/Mage/Catalog/Model/Product/Option/Type/Select.php

$valueCount = empty($value) ? 0 : count($value);

We simply solved it adding a @ in front of count call, thus swallowing any exception.

We wonder if is there any solution better than this, and if it's our installation or is a general bug on the magento.

**Comment by Flyingmana** [comment]
what is the exact warning you get there?

**Comment by xavitriu** [comment]
Exception: Warning: count(): Parameter must be an array or an object that implements Countable  in /app/code/core/Mage/Catalog/Model/Product/Option/Type/Select.php on line 57 in /app/code/core/Mage/Core/functions.php:207

**Comment by Sdfendor** [comment]
The better solution is to test whether something is countable. 
Use `is_countable()` ([PHP Net Documentation](https://www.php.net/manual/en/function.is-countable.php)) so something like `$valueCount = empty($value) || !is_countable($value) ? 0 : count($value)`.

To suppress the warning is only a short-time solution for versions 7.2 to 7.4. In PHP 8 this warning is no longer a warning but a type error. I've already encountered this type of error (we are using 8.0 with our OpenMage instance). 
![image](https://user-images.githubusercontent.com/2728018/132322615-01d5d7d5-2edc-4895-bf93-71f6f3c79af3.png)

**Comment by kiatng** [comment]
> The better solution is to test whether something is countable.
> Use `is_countable()` ([PHP Net Documentation](https://www.php.net/manual/en/function.is-countable.php)) to do something like `$valueCount = empty($value) || !is_countable($value) ? 0 : count($value)`.
> I noticed that the function is only available from 7.3 onwards. A polyfill in 7.2 could be something like `is_array($value) || $value instanceof Countable` to check whether `count()` can be used.
> 
> To suppress the warning is only a short-time solution for versions 7.2 to 7.4. In PHP 8 this warning is no longer a warning but a type error. I've already encountered this type of error (we are using 8.0 with our OpenMage instance).
> ![image](https://user-images.githubusercontent.com/2728018/132322615-01d5d7d5-2edc-4895-bf93-71f6f3c79af3.png)

If `$value` is an int or some value, then `$valueCount` should be 1.

```php
$valueCount = empty($value) 
    ? 0
    : (is_countable($value) ? count($value) : 1);
```

**Comment by henryhayes** [comment]
> I noticed that the function is only available from 7.3 onwards. A polyfill in 7.2 could be something like `is_array($value) || $value instanceof Countable` to check whether `count()` can be used.

This is a perfectly acceptable solution. However, we need to check where else this might be a problem.

@xavitriu can you please find out what exactly your `$value` variable contains as I can't replicate your problem on a vanilla install; and surely it should have been analysed before passing to `count()` anyway?

**Comment by Flyingmana** [comment]
in case its needed, here is a polyfill for the is_countable
https://github.com/PHPWatch/is_countable-polyfill/blob/master/src/is_countable.php

**Comment by Flyingmana** [comment]
fixed by https://github.com/OpenMage/magento-lts/pull/2040

**Comment by ADDISON74** [comment]
This is still an issue in OpenMage if PHP >8.0 is used. Error _"Exception: Warning: count(): Parameter must be an array or an object that implements Countable in ..."_ can be reproduced with other files too. I don't like putting the symbol @ in front of the function to suppress the warning/error.

I have doubts #2040 fixed this issue too.
