### ISSUE TITLE
Catalog Price Rules End Date not working as expected

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#443]
Catalog Price Rules End Date not working as expected. M 1934, LTS version

Problem: When setting a Catalog Price Rule to start 1-12 and end 31-12. For this to work we need to set start date _instead_ as 30-11 and end date to 30-12. Backend adminhtml US language. European Time. Server time (now) = Thu Feb  1 13:38:11 CET 2018 and corresponds with the actual time.

Problem also confirmed here:
- https://magento.stackexchange.com/questions/170961/magento-catalog-price-rule-date-not-working-properly#
- https://magento.stackexchange.com/questions/171093/magento-issue-with-dates-for-catalog-price-rule
- (possible solution) https://magento.stackexchange.com/questions/61045/catalog-price-rule-from-today-does-not-apply

![image](https://user-images.githubusercontent.com/652395/35678805-fe2722c2-0754-11e8-8933-f6a0ec580ce7.png)

In file 'Mage/CatalogRule/Model/Resource/Rule.php' I dont know why they are adding 1 day?

![image](https://user-images.githubusercontent.com/652395/35679011-caabcf64-0755-11e8-887e-d027cba68598.png)

**Comment by sreichel** [comment]
Can you please try patch from #434. Guess its the same issue.

**Comment by seansan** [comment]
​not the same;

I am testing ​a solution now will update later




Powered by Gmelius <https://gmelius.com?ref=mail>

**Comment by sreichel** [comment]
(@seansan removed my comment before your answer ... so also deleted it to keep it clean)

Just a reminder to me ... check timezone issues and customers last visit date - there was something wrong too.

**Comment by tomekjordan** [comment]
I dont remeber, but I thought it was fixed in 1931. Im using it, and there are no catalog price rules porblems anymore. Im in UTC+2 timezone

**Comment by tomekjordan** [comment]
UPDATE: I checked and I managed it by fixing 
catalogrule/observer::dailyCatalogUpdate

with AOE Scheduler to fit my timezone: 
from: Original: 0 1 * * *
to: 1 0 * * *
and it works for me (GMT+1)

**Comment by seansan** [comment]
A patch was shared in pull. Should fix it for all time zones without making
other changes.
Please test that and confirm.

**Comment by tomekjordan** [comment]
Tested. 100% works. Start date,end date for catalog rules know works properly (tested on GMT+1). Thanks

**Comment by tomekjordan** [comment]
HI. I tested it a bit in production, and I think something is still wrong. When I set Catalog Rule + press Apply Rules sometimes - dont know why - rules are deactivated the next day, and start to work +1 after that supposed. And I dont know why.... Maybe this is due to AEO Cron scheduler I use with a bit customized cron jobs for it:
catalog_product_index_price_reindex_all |   |   | 1 0 * * * | catalog/observer::reindexProductPrices
ORIGINAL was: 0 2 * * *
catalogrule_apply_all |   |   | 1 0 * * * | catalogrule/observer::dailyCatalogUpdate
ORIGINAL was 0 1 * * *

What you think about it?

**Comment by seansan** [comment]
Best you can do is quickly echo the 3 date times and push apply rules. See
how the dates come out.

**Comment by ryangrow** [comment]
I noticed this issue years ago, if the catalogrule_apply_all cron missed then the price rules would stop being applied later that evening. I was able to fix this by using a different time stamp to do the price rule calculations. Instead of using GMT, I am using local time, this is what is used when calculating price in the frontend anyways.

In Mage/CatalogRule/Model/Resource/Rule.php I changed: 
`        /** @var Mage_Core_Model_Date $coreDate */
        $coreDate  = $this->_factory->getModel('core/date');
        $timestamp = $coreDate->gmtTimestamp('Today');
`
to:
`$timestamp = Mage::app()->getLocale()->date(null, null, null, true)->get(Zend_Date::TIMESTAMP);`

**Comment by alexmorco** [comment]
Thanks for sharing this video tutorial, I was working to set catalog price rules in my Magento store, Your vide and this post helped me a lot, https://www.cloudways.com/blog/shopping-cart-and-catalog-price-rules-in-magento/.﻿

**Comment by Flyingmana** [comment]
I dont know much about the context, but to add one day (and subtract one second) is to have the rule active till end of the day you enter. else the timestamp would contain the start of the day, and the last day would not be covered anymore.

Cant say much about the rest, but sounds like there is a real problem

**Comment by ryangrow** [comment]
In your code you are adding a set amount of extra time (a day -1 sec) to the the rules "to time" (which is stored as a date in MySQL) this will work for your time zone, if your before GMT, but not if your after. The real cause of the problem is that the rules are calculated in GMT but should be calculated for the time zone. 

Ironically in my magento install I don't calculate price rules in a cron anymore, but I do it on the fly in MySQL when I get the product collection, and I avoid this whole mess, I also gave up on the price index as well.

**Comment by sreichel** [comment]
Should be fixed in #444.
