### ISSUE TITLE
How about SUPEE-10570v2?

### ISSUE THREAD

**Issue by rafaelpatro** [OpenMage/magento-lts#522]
Hi guys
I'd like to ask about SUPEE-10570 **v2**.
Seems that some issues were fixed after merged by this repository.
https://magento.stackexchange.com/questions/215292/security-patch-supee-10570-possible-issues

# Last LTS patch merged: Mar 9, 2018
![image](https://user-images.githubusercontent.com/13813964/45497060-371fdd00-b74d-11e8-828f-fbc45bdc5c19.png)

# Last Official patch update: Mar 28, 2018
![image](https://user-images.githubusercontent.com/13813964/45496982-faec7c80-b74c-11e8-9884-5cfefbadd287.png)

Was that [customer session issue](https://magento.stackexchange.com/questions/215292/security-patch-supee-10570-possible-issues) fixed in another PR?

**Comment by colinmollenhour** [comment]
Perhaps we should just disable the feature by changing this to `return false;`?

https://github.com/OpenMage/magento-lts/commit/fd5b9471dea8be3493e16b0487e0a312e5fea02a#diff-3907f9ecbef66cf19e0f9c32f64f54caR407

```php
    public function useValidateSessionPasswordTimestamp()
    {
        return true;
    }
```

I don't know the exact motivation behind this change, but it looks like it invalidates any sessions that were created before the most recent password update. Also should `useValidateSessionExpire` really always be true? This seems to prevent a session being used for longer than the original cookie lifetime. That is, if the cookie lifetime is 30 days and the user visits on the 23rd hour of the 29th day their session will still be invalidated in an hour rather than being given another 30 days. This seems like a bad "feature" to me.

**Comment by colinmollenhour** [comment]
> I agree. This can be improved by elongating the lifetime

Ahh, I spoke too soon, looks like that part was already addressed back in February. The magento-lts code is actually different than the upstream code in this regard (36a0afb8937fd6c358c507b3a59b7cf119fc3e8b) so perhaps the bug with the update doesn't affect this project the same way? I'm not sure I fully understand the original bug though.

**Comment by rafaelpatro** [comment]
Thanks! I'll test it soon

**Comment by jgeerdink** [comment]
It seems that the fix in SUPEE-10570v2 is removed in the latest versions 1.9.3.9 and even 1.9.3.10. So the checkout register account problem is still active in 1.9.3.9 and 1.9.3.10. It seems that V1 of SUPEE-10570 is implemented in 1.9.3.9 and 1.9.3.10.

**Comment by treestonemedia** [comment]
It's fixed on Magento 1.9.3.9 and was also fixed in patch SUPEE-10752
See here https://magento.stackexchange.com/questions/249426/update-magento-1-checkout-account-create-redirect-supee-10570v2-and-magento-1/251828#251828

**Comment by Flyingmana** [comment]
I would expect the latest magento version (1.9.4.0) includes all necessary patches

**Comment by pauldonnelly** [comment]
We're using a fresh install of 1.9.3.10 and this issue still exists.   Checking SUPEE-10570v2 it seems it's not been applied to 1.9.3.10. 
Wondering if it's OK to apply SUPEE-10570v2 on top of 1.9.3.10?

**Comment by tmotyl** [comment]
Can somebody sum up the issue, how to reproduce it/verify whether its fixed or not?

**Comment by eyes2design** [comment]
app/code/core/Mage/Core/Model/Session/Abstract/Varien.php is not fixed at line 487... 
https://magentary.com/glossary/supee-10570v2/
Guest Paypal accounts will fail to create.

**Comment by sreichel** [comment]
We are on 1.9.4.5 new ... i'd like to close.

**Comment by Flyingmana** [comment]
as of this updated answer(which was already linked here): https://magento.stackexchange.com/a/251828/3245 (and official patching recommendation)
the issue should be fixed since Magento 1.9.3.9
The used Fix is different then what the initial provided Patch did, but thats not uncommon for Magento.

So I will close this Issue
